DEVELOPMENT_PORT = 9007
TESTING_PORT = 9008
PRODUCTION_PORT = 9007


LOCAL_DB_NAME = "giani"
LOCAL_USER = "postgres"
LOCAL_HOST = "localhost"
LOCAL_PASSWORD = "12345"


ONDEV_DB_NAME = "giani"
ONDEV_USER = "yichun"
ONDEV_HOST = "localhost"
ONDEV_PASSWORD = "chachun88"


ONTEST_DB_NAME = "test_giani"
ONTEST_USER = "postgres"
ONTEST_HOST = "localhost"
ONTEST_PASSWORD = "12345"


PRODUCTION_DB_NAME = "giani"
PRODUCTION_USER = "yichun"
PRODUCTION_HOST = "localhost"
PRODUCTION_PASSWORD = "chachun88"
